### ISSUE TITLE
I'm writing nextjs and I'm having a problem with moralis

### ISSUE THREAD

**Issue by wangyangv1** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#14]
At the beginning, I used MoralisProvider in _app, but in my localhost website it gives an error
<img width="891" alt="image" src="https://user-images.githubusercontent.com/49341812/188637793-e5dffe20-60bd-4155-9d55-52b7d54f6853.png">
![image](https://user-images.githubusercontent.com/49341812/188637812-79542f0d-0251-41d1-acf8-7b4f5d9056b3.png)

**Comment by chinwan34** [comment]
I faced the same issues as well, it was because moralis has been updated to moralis-v1 recently.
You need to remove moralis using: yarn remove moralis
Then add moralis-v1 using: yarn add moralis-v1
You also need to remove react-moralis using: yarn remove react-moralis
Then add back: yarn add moralis-v1 react-moralis

**Comment by wangyangv1** [comment]
> I faced the same issues as well, it was because moralis has been updated to moralis-v1 recently. You need to remove moralis using: yarn remove moralis Then add moralis-v1 using: yarn add moralis-v1 You also need to remove react-moralis using: yarn remove react-moralis Then add back: yarn add moralis-v1 react-moralis

Thanks a bunch，it's so helpful

**Comment by wangyangv1** [comment]
You need to remove moralis using: yarn remove moralis Then add moralis-v1 using: yarn add moralis-v1 You also need to remove react-moralis using: yarn remove react-moralis Then add back: yarn add moralis-v1 react-moralis
